name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run build
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          REACT_APP_PHONE: ${{ secrets.REACT_APP_PHONE }}
          REACT_APP_EMAIL: ${{ secrets.REACT_APP_EMAIL }}
          REACT_APP_RELEASE_YEAR: ${{ secrets.REACT_APP_RELEASE_YEAR }}
          REACT_APP_SITE_NAME: ${{ secrets.REACT_APP_SITE_NAME }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
